function tau_viscous = ViscousFriction_fun(in1,in2)
%ViscousFriction_fun
%    TAU_VISCOUS = ViscousFriction_fun(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    03-May-2026 14:52:02

fv1 = in2(1,:);
fv2 = in2(2,:);
fv3 = in2(3,:);
fv4 = in2(4,:);
q1p = in1(1,:);
q2p = in1(2,:);
q3p = in1(3,:);
q4p = in1(4,:);
tau_viscous = [fv1.*q1p;fv2.*q2p;fv3.*q3p;fv4.*q4p];
end
